---

- name: install nano
  hosts: linux
  tasks:
    - name: see that nano is installed
      apt:
        name: nano
        state: latest
        update_cache: yes
        force_apt_get: yes
  
  
        
