#add your hosts in /etc/ansible/hosts file
#add your ssh private keys (ssh-add ~/.ssh/id_rsa)
---

- hosts: linux # Replace this once you add your hosts
  become: true # This makes it so Ansible becomes root
  tasks:
  - name: Upgrade all installed packages for Debian and Ubuntu
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  - name: Upgrade all installed packages for CentOS
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == "CentOS"
  - name: Upgrade all installed packages for openSUSE
    zypper:
      name: '*'
      state: latest
    when: ansible_distribution == "openSUSE Leap"

